query getUserProfile($id: ID!, $pib_id: ID!) {
  user(id: $id) {
    email
    wallet {
      balance
    }

    bits_registras(where: { pay_in_bit: { id: $pib_id } }) {
      status
      pay_in_bit {
        name
      }
    }
  }
}
